<?xml version='1.0'?>

<robot name="skid_steer_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="$(find carob_description)/urdf/carob_proto1.gazebo" />

	<!-- Scale the robot size to fit the environment -->
	<xacro:property name="scale" value="3.0" />

	<!-- Length along X-axis, Width along Y-axis, Height along Z-axis -->
	<xacro:property name="carob_width" value="${scale * 0.46}" />
	<xacro:property name="carob_length" value="${scale * 0.46}" />
	<xacro:property name="carob_height" value="${scale * 0.3}" />
	<xacro:property name="carob_mass" value="${scale * 10}" />

	<xacro:property name="base_x_offset" value="0" />

	<!-- inertia = 1/12*m(h^2+d^2) -->
	<xacro:property name="height_2" value="${carob_height * carob_height}" />
	<xacro:property name="width_2" value="${carob_width * carob_width}" />
	<xacro:property name="length_2" value="${carob_length * carob_length}" />
	<xacro:property name="carob_inertia_xx" value="${carob_mass/12.0 * (height_2 + width_2)}" />
	<xacro:property name="carob_inertia_yy" value="${carob_mass/12.0 * (height_2 + length_2)}" />
	<xacro:property name="carob_inertia_zz" value="${carob_mass/12.0 * (width_2 + length_2)}" />
	<xacro:property name="carob_i_x_pos" value="${base_x_offset}" />
	<xacro:property name="carob_i_z_pos" value="${carob_height/3.0}" />

	<xacro:property name="wheel_length" value=".135" />
	<xacro:property name="wheel_radius" value=".15" />
	<xacro:property name="wheel_mass" value="${scale * 1}" />
	<xacro:property name="wheel_inertia" value="${scale * 1e-3}" />
	<xacro:property name="wheel_x_offset" value="${base_x_offset + carob_length/2.0}" />
	<xacro:property name="wheel_y_offset" value="${carob_width/2.0 - wheel_length/2.0}" />

	<xacro:property name="wheel_effort" value="1000" />  <!-- 10000-->
	<xacro:property name="wheel_velocity" value="10" /> <!-- 1000-->
	<xacro:property name="joint_damping" value="0" />   <!-- 1.0-->
	<xacro:property name="joint_friction" value="1.0" />  <!-- 1.0-->
	
	<xacro:property name="wheel_kp" value="1000000.0" /> <!-- 1000000-->
	<xacro:property name="wheel_kd" value="100.0" /> <!-- 100-->
	<xacro:property name="wheel_mu1" value="1" /> <!-- 1-->
	<xacro:property name="wheel_mu2" value="1" /> <!-- 1-->
	<xacro:property name="wheel_slip1" value="1" /> <!-- 0.5-->
	<xacro:property name="wheel_slip2" value="0" /> <!-- 0-->

	<xacro:property name="caterpillar_mass" value="20" />
	<xacro:property name="cabin_mass" value="70" />
	<xacro:property name="chassis_mass" value="80" />
	<xacro:property name="cameraSize" value="0.05"/>
	<xacro:property name="cameraMass" value="0.1"/>

	<!-- Materials for rviz-->
	<material name="grey">
		<color rgba=".2 .2 .2 1"/>
	</material>
	<material name="white">
		<color rgba="1 1 1 1"/>
	</material>
	<material name="orange">
		<color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
	</material>

	<!-- Ground-->
	<link name="robot_footprint"></link>

	<link name="map">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="0.001 0.001 0.001" />
			</geometry>
		</visual>
	</link>

	<joint name="map_to_robot_footprint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0" />
		<parent link="map"/>
		<child link="robot_footprint"/>
	</joint>


	<!-- Caterpillars-->

	<!-- Left Caterpillar-->
	<joint name="left_caterpillar_joint" type="fixed">
		<origin xyz="0.04 0.03 -0.01" rpy="0 0 0" />
		<parent link="left_chassis" />
		<child link="left_caterpillar" />
	</joint>

	<link name='left_caterpillar'>
		<inertial>
			<mass value="${caterpillar_mass}"/>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<inertia
				ixx="${carob_inertia_xx}" ixy="0" ixz="0"
				iyy="${carob_inertia_yy}" iyz="0"
				izz="${carob_inertia_zz}" />
		</inertial>

		<collision>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<geometry>
				<mesh filename="package://carob_description/meshes/Oruga.stl"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<geometry>
				<mesh filename="package://carob_description/meshes/Oruga.stl"/>
			</geometry>
			<material name="grey"/>
		</visual>
	</link>

	<!-- Right Caterpillar-->
	<joint name="right_caterpillar_joint" type="fixed">
		<origin xyz="0.04 -0.03 -0.01" rpy="0 0 0" />
		<parent link="right_chassis" />
		<child link="right_caterpillar" />
	</joint>

	<link name='right_caterpillar'>
		<inertial>
			<mass value="${caterpillar_mass}"/>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<inertia
				ixx="${carob_inertia_xx}" ixy="0" ixz="0"
				iyy="${carob_inertia_yy}" iyz="0"
				izz="${carob_inertia_zz}" />
		</inertial>

		<collision>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<geometry>
				<mesh filename="package://carob_description/meshes/Oruga.stl"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<geometry>
				<mesh filename="package://carob_description/meshes/Oruga.stl"/>
			</geometry>
			<material name="grey"/>
		</visual>      
	</link>

<!-- Body-->

	<!-- Left Chassis-->
	<joint name="left_chassis_joint" type="fixed">
		<origin xyz="-0.135 0.725 -0.927" rpy="0 0 0" />
		<parent link="cabin" />
		<child link="left_chassis" />
	</joint>

	<link name='left_chassis'>
		<inertial>
			<mass value="1"/>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<inertia
				ixx="${carob_inertia_xx}" ixy="0" ixz="0"
				iyy="${carob_inertia_yy}" iyz="0"
				izz="${carob_inertia_zz}" />
		</inertial>
			<collision>
				<origin xyz="0 0 0" rpy=" 0 0 0"/>
				<geometry>
						<mesh filename="package://carob_description/meshes/ChasisIzquierdo.stl"/>
					</geometry>
			</collision>
		<visual>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<geometry>
					<mesh filename="package://carob_description/meshes/ChasisIzquierdo.stl"/>
			</geometry>
			<material name="white"/>
		</visual>      
	</link>	

	
	<!-- Right Chassis-->
	<joint name="right_chassis_joint" type="fixed">
		<!-- Fixed problem in y due to meshes issue-->
		<origin xyz="-0.135 -0.71 -0.927" rpy="0 0 0" /> 
		<parent link="cabin" />
		<child link="right_chassis" />
	</joint>

	<link name='right_chassis'>
		<inertial>
			<mass value="1"/>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<inertia
				ixx="${carob_inertia_xx}" ixy="0" ixz="0"
				iyy="${carob_inertia_yy}" iyz="0"
				izz="${carob_inertia_zz}" />
		</inertial>

		<collision>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<geometry>
				<mesh filename="package://carob_description/meshes/ChasisDerecho.stl"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<geometry>
				<mesh filename="package://carob_description/meshes/ChasisDerecho.stl"/>
			</geometry>
			<material name="white"/>
		</visual>      
	</link>	

	<!-- Cabin-->
	<joint name="cabin" type="fixed">
		<origin xyz="0 0 5.19" rpy="0 0 0" />
		<parent link="robot_footprint" />
		<child link="cabin" />
	</joint>

	<link name='cabin'>
		<inertial>
			<mass value="${carob_mass}"/>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<inertia
				ixx="${carob_inertia_xx}" ixy="0" ixz="0"
				iyy="${carob_inertia_yy}" iyz="0"
				izz="${carob_inertia_zz}" />
		</inertial>

		<collision>
			<origin xyz="${base_x_offset} 0 0" rpy=" 0 0 0"/>
			<geometry>
				<mesh filename="package://carob_description/meshes/Cabina.stl"/>
			</geometry>
		</collision>
			<visual>
			<origin xyz="${base_x_offset} 0 0" rpy=" 0 0 0"/>
			<geometry>
				<mesh filename="package://carob_description/meshes/Cabina.stl"/>
			</geometry>
			<material name="orange"/>
		</visual>      
	</link>

	<!-- Front Bar-->
	<joint name="bar_joint" type="fixed">
		<origin xyz="0.59 0 -0.475" rpy="0 0 0" />
		<parent link="cabin" />
		<child link="bar" />
	</joint>

	<link name='bar'>
		<inertial>
			<mass value="1"/>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<inertia
				ixx="${carob_inertia_xx}" ixy="0" ixz="2.5"
				iyy="${carob_inertia_yy}" iyz="0"
				izz="${carob_inertia_zz}" />
		</inertial>

		<collision>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<geometry>
				<mesh filename="package://carob_description/meshes/Barra.stl"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 0" rpy=" 0 0 0"/>
			<geometry>
				<mesh filename="package://carob_description/meshes/Barra.stl"/>
			</geometry>
			<material name="white"/>
		</visual>      
	</link>

<!-- Sensors -->

<!-- Cameras -->

	<!-- Front Camera -->
	<joint name="front_camera_joint" type="fixed">
		<axis xyz="0 0 0" />
		<origin xyz="0.5 0 0.5" rpy="0 0.5707 0"/>
		<parent link="cabin"/>
		<child link="front_camera"/>
	</joint> 

	<link name="front_camera">
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
			</geometry>
		</collision>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
			</geometry>
			<material name="green"/>
		</visual>

		<inertial>
			<mass value="${cameraMass}" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
		</inertial>
	</link>	
	
	<!-- Front laser -->
	<joint name="hokuyo_joint" type="fixed">
		<axis xyz="0 1 0" />
		<origin xyz="0.7 0 -0.5" rpy="0 0 0"/>
		<parent link="cabin"/>
		<child link="front_laser"/>
	</joint>
	
	<link name="front_laser">
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.1 0.1 0.1"/>
			</geometry>
		</collision>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://carob_description/meshes/hokuyo.dae"/>
			</geometry>
		</visual>

		<inertial>
			<mass value="1e-5" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
		</inertial>
	</link>

		<!-- IMU -->
	<joint name="imu_joint" type="fixed">
	      <axis xyz="1 0 0"/>	      
		  <origin xyz="0 0 1" rpy="0 0 0"/>	      
	      <parent link="cabin"/>
	      <child link="imu"/>
	  </joint>

	  <link name="imu">
	    <inertial>
				<origin xyz="0.0 0 0.01" rpy="0 0 0" />
				<mass value="0.05" />
				<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
		  </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size=".001 .001 .001"/>
        </geometry>
      </collision>
	  </link>

	  <!-- GPS -->
		<joint name="gps_joint" type="fixed">
		  <axis xyz="1 0 0"/>	      
		  <origin xyz="0 0 2" rpy="0 0 0"/>
	    <parent link="cabin"/>
	    <child link="gps"/>
		</joint>

	  <link name="gps">
	    <inertial>
				<origin xyz="0.0 0 0.01" rpy="0 0 0" />
				<mass value="0.05" />
				<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
		  </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <box size=".001 .001 .001"/>
        </geometry>
      </collision>
	  </link>

<!-- Wheels -->

	<!-- left front wheel -->
	<joint type="continuous" name="left_front_wheel_hinge">
		<origin xyz="0.5 0 -0.08" rpy="0 0 0"/>
		<child link="left_front_wheel"/>
		<parent link="left_caterpillar"/>
		<axis xyz="0 1 0" rpy="0 0 0"/>
		<limit effort="${wheel_effort}" velocity="${wheel_velocity}"/>
		<joint_properties damping="${joint_damping}" friction="${joint_friction}" />
	</joint>

	<link name="left_front_wheel">
		<inertial>
			<mass value="${wheel_mass}"/>
			<origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
			<inertia
				ixx="${wheel_inertia}" ixy="0" ixz="0"
				iyy="${wheel_inertia}" iyz="0"
				izz="${wheel_inertia}" />
		</inertial>
		<collision name="left_front_wheel_collision">
			<origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
			</geometry>
			<surface>
				<friction>
					<fdir1>1 0 0</fdir1>
					<kp>${wheel_kp}</kp> <!-- kp and kd for rubber -->
					<kd>${wheel_kd}</kd>
					<mu>${wheel_mu1}</mu>
					<mu2>${wheel_mu2}</mu2>
					<slip1>${wheel_slip1}</slip1>
					<slip2>${wheel_slip2}</slip2>
				</friction>
			</surface>
		</collision>
		<visual name="left_front_wheel_visual">
			<transparency>1</transparency>
			<origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
			</geometry>
			<material name="grey"/>
			<transparency>1</transparency>
		</visual>
	</link>

	<!-- left back wheel -->
	<joint type="continuous" name="left_back_wheel_hinge">
		<origin xyz="-0.5 0 -0.08" rpy="0 0 0"/>
		<child link="left_back_wheel"/>
		<parent link="left_caterpillar"/>
		<axis xyz="0 1 0" rpy="0 0 0"/>
		<limit effort="${wheel_effort}" velocity="${wheel_velocity}"/>
		<joint_properties damping="${joint_damping}" friction="${joint_friction}" />
	</joint>

	<link name="right_back_wheel">
		<inertial>
			<mass value="${wheel_mass}"/>
			<origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
			<inertia
				ixx="${wheel_inertia}" ixy="0" ixz="0"
				iyy="${wheel_inertia}" iyz="0"
				izz="${wheel_inertia}" />
		</inertial>
		<collision name="right_back_wheel_collision">
			<origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
			</geometry>
				<surface>
					<friction>
						<fdir1>1 0 0</fdir1>
						<kp>${wheel_kp}</kp> <!-- kp and kd for rubber -->
						<kd>${wheel_kd}</kd>
						<mu>${wheel_mu1}</mu>
						<mu2>${wheel_mu2}</mu2>
						<slip1>${wheel_slip1}</slip1>
						<slip2>${wheel_slip2}</slip2>
					</friction>
				</surface>
		</collision>
			<visual name="right_back_wheel_visual">
				<origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
				</geometry>
				<material name="grey"/>
			</visual>
	</link>

	<!-- right back wheel -->
	<joint type="continuous" name="right_back_wheel_hinge">
		<origin xyz="-0.5 0 -0.08" rpy="0 0 0"/>
		<child link="right_back_wheel"/>
		<parent link="right_caterpillar"/>
		<axis xyz="0 1 0" rpy="0 0 0"/>
		<limit effort="${wheel_effort}" velocity="${wheel_velocity}"/>
		<joint_properties damping="${joint_damping}" friction="${joint_friction}" />
	</joint>

	<link name="left_back_wheel">
		<inertial>
			<mass value="${wheel_mass}"/>
			<origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
			<inertia
				ixx="${wheel_inertia}" ixy="0" ixz="0"
				iyy="${wheel_inertia}" iyz="0"
				izz="${wheel_inertia}" />
		</inertial>
		<collision name="left_back_wheel_collision">
			<origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
			</geometry>
			<surface>
				<friction>
					<fdir1>1 0 0</fdir1>
					<kp>${wheel_kp}</kp> <!-- kp and kd for rubber -->
					<kd>${wheel_kd}</kd>
					<mu>${wheel_mu1}</mu>
					<mu2>${wheel_mu2}</mu2>
					<slip1>${wheel_slip1}</slip1>
					<slip2>${wheel_slip2}</slip2>
				</friction>
			</surface>
		</collision>
		<visual name="left_back_wheel_visual">
			<origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
			<geometry>
				<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
			</geometry>
			<material name="grey"/>		
		</visual>
	</link>

	<!-- right front wheel -->
	<joint type="continuous" name="right_front_wheel_hinge">
		<origin xyz="0.5 0 -0.08" rpy="0 0 0"/>
		<child link="right_front_wheel"/>
		<parent link="right_caterpillar"/>
		<axis xyz="0 1 0" rpy="0 0 0"/>
		<limit effort="${wheel_effort}" velocity="${wheel_velocity}"/>
		<joint_properties damping="${joint_damping}" friction="${joint_friction}" />
	</joint>wheel

	<link name="right_front_wheel">
		<inertial>
			<mass value="${wheel_mass}"/>
			<origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
			<inertia
				ixx="${wheel_inertia}" ixy="0" ixz="0"
				iyy="${wheel_inertia}" iyz="0"
				izz="${wheel_inertia}" />
		</inertial>
			<collision name="right_front_wheel_collision">
				<origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
				</geometry>
				<surface>
					<friction>
						<fdir1>1 0 0</fdir1>
						<kp>${wheel_kp}</kp> <!-- kp and kd for rubber -->
						<kd>${wheel_kd}</kd>
						<mu>${wheel_mu1}</mu>
						<mu2>${wheel_mu2}</mu2>
						<slip1>${wheel_slip1}</slip1>
						<slip2>${wheel_slip2}</slip2>
					</friction>
				</surface>
			</collision>
		<visual name="right_front_wheel_visual">
				<transparency>1</transparency>
				<origin xyz="0 0 0" rpy=" 0 1.5707 1.5707"/>
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
				</geometry>
				<material name="grey"/>
		</visual>
	</link>
	
</robot>
